tests/functions.sh.in: Rename variables $status and $i when running cleanups.
This causes conflicts if a cleanup hook happens to use a variable with
the same name.

(cherry picked from commit 77e64c913d6281142811d5b78e84f13c1c97a8ce)

diff --git a/tests/functions.sh.in b/tests/functions.sh.in
--- a/tests/functions.sh.in
+++ b/tests/functions.sh.in
@@ -43,17 +43,17 @@ cleanup_fn ()
 
 _run_cleanup_hooks ()
 {
-    local status=$? i
+    local _status=$? _i
 
     set +e
     trap '' INT QUIT TERM EXIT ERR
-    echo $0: run cleanup hooks: exit code $status
+    echo $0: run cleanup hooks: exit code $_status
 
-    for (( i = 0; i < ${#_cleanup_hook[@]}; ++i )); do
-        ${_cleanup_hook[i]}
+    for (( _i = 0; _i < ${#_cleanup_hook[@]}; ++_i )); do
+        ${_cleanup_hook[_i]}
     done
 
-    exit $status
+    exit $_status
 }
 trap _run_cleanup_hooks INT QUIT TERM EXIT ERR
 
