tests: Use wine taskkill /pid to kill Windows process ID.
Fix test-foreground.sh so it works under Wine.  The clue was that
getpid() under Wine does not return the Unix PID.  Instead it returns
a “Windows process ID” which is a different thing.  When wineserver is
managing the Wine processes we can kill them by Windows process ID
using:

  wine taskkill /f /pid <PID>

It's unclear why /f is required, but it doesn't work without it.

Longer discussion: https://forum.winehq.org/viewtopic.php?f=2&t=34300

diff --git a/tests/functions.sh.in b/tests/functions.sh.in
--- a/tests/functions.sh.in
+++ b/tests/functions.sh.in
@@ -218,20 +218,24 @@ kill_nbdkit ()
 {
     local pid=$1 i
 
-    # Start with SIGTERM, and wait for graceful exit
-    kill $pid
-    for i in {1..60}; do
-        if ! kill -0 $pid 2>/dev/null; then
-            break
+    if ! is_windows; then
+        # Start with SIGTERM, and wait for graceful exit
+        kill $pid
+        for i in {1..60}; do
+            if ! kill -0 $pid 2>/dev/null; then
+                break
+            fi
+            sleep 1
+        done
+        # If nbdkit has not exited, try SIGKILL and fail the test
+        if test $i = 60; then
+            echo "error: nbdkit pid $pid failed to respond to SIGTERM"
+            kill -9 $pid
+            # Append our failure after other cleanups
+            cleanup_fn exit 1
         fi
-        sleep 1
-    done
-    # If nbdkit has not exited, try SIGKILL and fail the test
-    if test $i = 60; then
-        echo "error: nbdkit pid $pid failed to respond to SIGTERM"
-        kill -9 $pid
-        # Append our failure after other cleanups
-        cleanup_fn exit 1
+    else
+        wine taskkill /f /pid $pid
     fi
 }
 
