tests: Add a helper function which waits for nbdkit to start up.
This assumes bashisms, but bash is required to run the tests.

This is mostly refactoring.  However the changes (simplifications) are
quite substantial:

 - Since the new start_nbdkit helper function cleans up nbdkit on
   exit, most scripts no longer need to deal with the pid or kill the
   pid in the cleanup function.

 - As a result, cleanup functions are radically simpler, and often
   disappear completely.

 - Also removed the comment "# The cleanup() function is called
   implicitly on exit" passim partly because the cleanup functions
   have mostly been removed and partly because it should be clear from
   looking at functions.sh.

There is one additional change: In the test-memory*.sh tests, nbdkit
used to run in the foreground, but that seems to be a consequence of
some left over debugging.  I changed it so they work like the other
tests.

diff --git a/tests/functions.sh.in b/tests/functions.sh.in
--- a/tests/functions.sh.in
+++ b/tests/functions.sh.in
@@ -57,6 +57,39 @@ _run_cleanup_hooks ()
 }
 trap _run_cleanup_hooks INT QUIT TERM EXIT ERR
 
+# start_nbdkit -P pidfile args...
+#
+# Run nbdkit with args and wait for it to start up.  If it fails to
+# start up, exit with an error message.  Also a cleanup handler is
+# installed automatically which kills nbdkit on exit.
+start_nbdkit ()
+{
+    # -P <pidfile> must be the first two parameters.
+    if [ "$1" != "-P" ]; then
+       echo "$0: start_nbdkit: -P <pidfile> option must be first"
+       exit 1
+    fi
+    pidfile="$2"
+
+    # Run nbdkit.
+    nbdkit "$@"
+
+    # Wait for the pidfile to appear.
+    for i in {1..10}; do
+        if test -f "$pidfile"; then
+            break
+        fi
+        sleep 1
+    done
+    if ! test -f "$pidfile"; then
+        echo "$0: start_nbdkit: PID file $pidfile was not created"
+        exit 1
+    fi
+
+    # Kill nbdkit on exit.
+    cleanup_fn kill "$(cat "$pidfile")"
+}
+
 # foreach_plugin f [args]
 #
 # For each plugin that was built, run the function or command f with
