tests/functions.sh.in: If requires Linux, check binary is compiled for Linux.
The AF_VSOCK test was not being skipped correctly under Wine.  This is
because the test for the Linux host kernel found the kernel.  What we
also want to do is check that the binary has been compiled for Linux,
so we know it is not running under emulation.

diff --git a/tests/functions.sh.in b/tests/functions.sh.in
--- a/tests/functions.sh.in
+++ b/tests/functions.sh.in
@@ -103,7 +103,17 @@ requires_linux_kernel_version ()
 {
     local kver
 
-    # Test the kernel is Linux.
+    # Check that nbdkit was built for Linux.  This can appear to be a
+    # peculiar test, but if we cross-compiled nbdkit for Windows and
+    # are running it under Wine then the host kernel will still be
+    # Linux, but the test will fail anyway.
+    host_os="$(nbdkit --dump-config | grep ^host_os | cut -d= -f2)"
+    if [[ ! "$host_os" =~ linux ]]; then
+        echo "$0: binary was built for $host_os (not Linux), skipping test"
+        exit 77
+    fi
+
+    # Test the host kernel is Linux.
     requires test "$(uname -s)" = "Linux"
 
     # Test that it's the minimum version.
